# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
	
	config.vm.define "jon" do |jon|
		jon.vm.box = "ubuntu/trusty64"
		jon.vm.hostname = "hubot-dev"
		jon.vm.provision "shell", path: "scripts/provision.sh"
		jon.vm.provision "shell", path: "scripts/node.sh"
		jon.vm.provision "shell", path: "scripts/ansible.sh"
		jon.vm.provision "shell", path: "scripts/vim.sh"
	end
end
